Add travis-ci config
centrifuge/substrate-pallet-multi-account pull request #1
Opened 2020-03-12 12:10 UTC by ivanceras

Note: the `--locked` flag in cargo build was remove, since it was causing a build error. 
The env `secret` is also commented out

2020-03-13 07:13 UTC, philipstanislaus requested changes
Thanks @ivanceras. 

Most of the changes you made are not applicable to this pallet though – I probably makes sense to close this PR and only include the codecov config in a new onei90-=.

2020-03-13 07:13 UTC, philipstanislaus commented on .travis.yml
> -- rustup component add rustfmt
Why remove this?

2020-03-13 07:13 UTC, philipstanislaus commented on .travis.yml
> -- cargo fmt -- --check
Why remove this? Rustfmt is used intentionally here

2020-03-13 07:13 UTC, philipstanislaus commented on .travis.yml
> +  - df -h
We don't need this, there is nothing written to disk in the tests.

2020-03-13 07:13 UTC, philipstanislaus commented on scripts/init.sh
> +echo "*** Initializing WASM build environment"
Why is this included? The module does not use WASM at all.

2020-03-13 07:13 UTC, philipstanislaus commented on .travis.yml
> +      script: travis_wait 180 ./ci/docker.sh
I don't think we should publish a docker image of a library/module, but maybe I'm missing something – what's the reasoning behind that?

2020-03-18 19:39 UTC, ivanceras commented
I'll close this one and create a new PR.

2020-03-18 19:39 UTC, closed without merging